// this code is generated by ckc code master.
// his website is at https://ckclol.github.io

const deg = 6;
const hr = document.querySelector('#h');
const mi = document.querySelector('#m');
const se = document.querySelector('#s');
let ctz = new Date();
ctz.setFullYear(2075);
ctz.setMonth(7);
ctz.setDate(12);
ctz.setHours(9);
ctz.setMinutes(34); 
ctz.setSeconds(11);

hr.style.transform = `rotateZ(${(hr)*(mm/12)}deg)`;
mi.style.transform = `rotateZ(${mi}*deg)`;
se.style.transform = `rotateZ(${se}*deg)`;
})
